services:
  stan:
    build: .
    volumes:
      - stan_data:/code/data
    ports:
      - "8813:8813"
    restart: unless-stopped
    environment:
      STAN: ${STAN}
      whiteids: ${whiteids}
      rollback: ${rollback}

volumes:
  stan_data:
